# Generated by Django 5.2.4 on 2025-08-04 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^(\\(?\\+?[0-9]*\\)?)?[0-9_\\- \\(\\)]*$', 'international dialing code at the start and digits only.')]),
        ),
    ]
