# Generated by Django 5.2.4 on 2025-08-04 16:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=50)),
                ('alert_type', models.CharField(choices=[('TS', 'THRESHOLD'), ('D', 'DURATION')], default='D', max_length=2)),
                ('comparison', models.CharField(choices=[('>', 'greaterThan'), ('<', 'lessThan'), ('=', 'equal')], default='=', max_length=1)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=300))),
                ('is_active', models.BooleanField(default=True)),
                ('has_triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
