# Generated by Django 5.2.4 on 2025-08-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_triggeredalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('threshold', 'THRESHOLD'), ('duration', 'DURATION')], max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='comparison',
            field=models.CharField(choices=[('>', 'greaterThan'), ('<', 'lessThan'), ('=', 'equal')], max_length=1),
        ),
    ]
