# Generated by Django 5.2.4 on 2025-08-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_alert_alert_type_alter_alert_comparison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='target_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='triggeredalert',
            name='trigger_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
