# Generated by Django 5.2.4 on 2025-08-08 05:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alter_alert_target_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('user', 'stock_symbol', 'comparison', 'target_price', 'duration')},
        ),
    ]
