# Generated by Django 5.2.4 on 2025-08-08 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alter_alert_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together=set(),
        ),
    ]
