# Generated by Django 5.2.4 on 2025-08-11 03:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alter_alert_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='triggeredalert',
            name='attempts_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='triggeredalert',
            name='notification_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triggeredalert',
            name='notification_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('sent', 'SENT'), ('fail', 'FAIL')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='target_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='triggeredalert',
            index=models.Index(fields=['notification_status'], name='alerts_trig_notific_de890d_idx'),
        ),
    ]
